apiVersion: apps/v1
kind: Deployment
metadata:
  name: order_service
  labels:
    app: order_service
    team: f1-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order_service
  template:
    metadata:
      labels:
        app: order_service
        team: f1-demo
    spec:
      containers:
        - name: order_service
          image: {{.Values.image}}
          ports:
            - containerPort: 7002
          env:
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory_service:7001"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 7002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7002
            initialDelaySeconds: 5
            periodSeconds: 10
